<?php 
// variables.php 

// Origine : perso, client, OpenClassrooms ou From Scratch
// Type : parcours, exercice, commande ou perso 
$achievements = [
	
	[
		'realization_id'  =>  1002,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Riding Cities',
		'description'  =>  'Projet 2 - Premiers pas sur le langage HTML',
		'full_description'  =>  'Page internet du site (Riding Cities) d\'une association sportive dans la pratique du skate',
		'image'  =>  'riding-cities.png',
		'alt_image'  =>  'Page internet du site Riding Cities',
		'title_image'  =>   'Page internet du site (Riding Cities) d\'une association sportive dans la pratique du skate',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/riding-cities/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1003,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Booki',
		'description'  =>  'Projet 3 - Créez la page d\'accueil d\'une agence de voyage avec HTML & CSS',
		'full_description'  =>  'Site Internet qui permette aux usagers de trouver des hébergements et des activités dans la ville de leur choix',
		'image'  =>  'booki.png',
		'alt_image'  =>  'Page internet du site Booki',
		'title_image'  =>   'Site Internet qui permette aux usagers de trouver des hébergements et des activités dans la ville de leur choix',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/booki/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1004,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Simpl Vintage',
		'description'  =>  'Projet 4 - Créer un site complet avec WordPress sans utiliser de code',
		'full_description'  =>  'Site simple pour promouvoir l\'ouverture de showroom',
		'image'  =>  'simpl-vintage.png',
		'alt_image'  =>  'Page internet du site Simpl Vintage',
		'title_image'  =>   'Site simple pour promouvoir l\'ouverture de showroom',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'http://stephane-mouron.fr/simpl-vintage/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1005,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'The Artbox',
		'description'  =>  'Projet 5 - Premiers pas sur le langage PHP',
		'full_description'  =>  'Refonte d\'un site HTML en PHP',
		'image'  =>  'the-artbox.png',
		'alt_image'  =>  'Page internet du site The Artbox',
		'title_image'  =>   'Refonte d\'un site HTML en PHP',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/the-artbox/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1006,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Planty',
		'description'  =>  'Projet 6 - Personnaliser une thème WordPress pour une startup avec HTML, CSS et Php',
		'full_description'  =>  'Création du site avec WordPress suivant la maquette Figma',
		'image'  =>  'planty.png',
		'alt_image'  =>  'Page internet du site Planty',
		'title_image'  =>   'Création du site avec WordPress suivant la maquette Figma',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  true,
		'guthemberg'  =>  true,
		'elementor'  =>  false,
		'link'  =>  'http://stephane-mouron.fr/planty/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1007,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Chic-Dressing',
		'description'  =>  'Projet 7 - Optimiser un site WordPress existant pour une marque de vêtements',
		'full_description'  =>  'Optimisation (performances et SEO) du site suivant les recommandations',
		'image'  =>  'chic-dressing.png',
		'alt_image'  =>  'Page internet du site Chic-Dressing',
		'title_image'  =>   'Optimisation (performances et SEO) du site suivant les recommandations',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  true,
		'guthemberg'  =>  false,
		'elementor'  =>  true,
		'link'  =>  'http://stephane-mouron.fr/chic-dressing/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1008,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Print It',
		'description'  =>  'Projet 8 - Premiers pas sur le langage JavaScipt',
		'full_description'  =>  'Amélioration d\'un site avec remplacement d\'une bannière par un carrousel en JavaScript',
		'image'  =>  'print-it-js.png',
		'alt_image'  =>  'Page internet du site Print-it-JS',
		'title_image'  =>   'Amélioration d\'un site avec remplacement d\'une bannière par un carrousel en JavaScript',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/print-it/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1009,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Koukaki - Fleurs d\'oranger & chats errants',
		'description'  =>  'Projet 9 - Améliorer le site d\'un studio d\'animation avec JavaScript et des animations CSS',
		'full_description'  =>  'Amélioration d\'un site avec remplacement d\'une bannière par un carrousel en JavaScript',
		'image'  =>  'koukaki.png',
		'alt_image'  =>  'Page internet du site Koukaki',
		'title_image'  =>   'Amélioration d\'un site avec remplacement d\'une bannière par un carrousel en JavaScript',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  true,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  true,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/koukaki/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1010,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Med-It',
		'description'  =>  'Projet 10 - Débuggez et testez un site WordPress d\'outillage médical',
		'full_description'  =>  'Débuggez et testez le site WordPress d\'outillage médical de la société Med-It',
		'image'  =>  'medit.png',
		'alt_image'  =>  'Page internet du site Med-It débuggé',
		'title_image'  =>   'Débuggez et testez le site WordPress d\'outillage médical de la société Med-It',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  true,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  true,
		'guthemberg'  =>  true,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/med-it/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1011,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Nathalie Mota',
		'description'  =>  'Projet 11 - Créer un sit WordPress complexe pour une photographe freelance',
		'full_description'  =>  'Créer un site WordPress complexe pour une photographe freelance',
		'image'  =>  'nathalie_mota.png',
		'alt_image'  =>  'Page internet du site de Nathalie Mota',
		'title_image'  =>   'Créer un site WordPress complexe pour une photographe freelance',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  true,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  true,
		'guthemberg'  =>  true,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/nathalie-mota/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1012,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Emoving',
		'description'  =>  'Projet 12 - Planifiez le développement d\'un site de vente de vélos électriques',
		'full_description'  =>  'Planifiez le développement d\'un site de vente de vélos électriques',
		'image'  =>  'emoving.png',
		'alt_image'  =>  'Page e-commerce d\'Emoving',
		'title_image'  =>   'Planifiez le développement d\'un site de vente de vélos électriques',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  true,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  true,
		'guthemberg'  =>  false,
		'elementor'  =>  true,
		'link'  =>  'https://stephane-mouron.fr/emoving/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1013,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'parcours',
		'title'  =>  'Portfolio WordPress',
		'description'  =>  'Projet 13 - Créer et publier votre portfolio de développeur',
		'full_description'  =>  'Créer et publier votre portfolio de développeur',
		'image'  =>  'portfolio_wp.png',
		'alt_image'  =>  'Portfolio Stephane Mouron',
		'title_image'  =>   'Créer et publier votre portfolio de développeur',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  true,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  true,
		'guthemberg'  =>  true,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/portfolio/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1101,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'exercice',
		'title'  =>  'Carnet de voyage de Totor le Taureau',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours : Apprenez à créer votre site web avec HTML5 et CSS3. Puis modification d\'éléments visuels et ajout d\'effets en CSS.',
		'image'  =>  'carnet-de-voyage-de-totor.png',
		'alt_image'  =>  'Site de Totor le taureau',
		'title_image'  =>   'Suite au cours : Apprenez à créer votre site web avec HTML5 et CSS3. Puis modification d\'éléments visuels et ajout d\'effets en CSS.',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/OpenClassrooms/Carnet-de-voyage-de-Totor/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1102,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'exercice',
		'title'  =>  'CV personnel',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours : Apprenez à créer votre site web avec HTML5 et CSS3. Puis mise à jour et remise en forme ensuite ',
		'image'  =>  'cv.png',
		'alt_image'  =>  'CV personnel',
		'title_image'  =>   'Suite au cours : Apprenez à créer votre site web avec HTML5 et CSS3. Puis mise à jour et remise en forme ensuite ',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/cv/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1103,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'exercice',
		'title'  =>  'Site de la photographe Robbie Lens',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours : Créez votre site web avec HTML5 et CSS3',
		'image'  =>  'robbie-lens.png',
		'alt_image'  =>  'Site de la photographe Robbie-Lens',
		'title_image'  =>   'Suite au cours : Créez votre site web avec HTML5 et CSS3',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/OpenClassrooms/Robbie-Lens/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1104,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'exercice',
		'title'  =>  'Site de recettes de cuisine',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours : Concevez votre site web avec PHP et MySQL',
		'image'  =>  'site_de recettes de cuisine.png',
		'alt_image'  =>  'Site de recettes de cuisine',
		'title_image'  =>   'Suite au cours : Concevez votre site web avec PHP et MySQL',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/OpenClassrooms/recettes/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1105,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'exercice',
		'title'  =>  'BricoTips',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours : Allez plus loin avec WordPress',
		'image'  =>  'bricotips.png',
		'alt_image'  =>  'Lexique sur les outils de bricolage',
		'title_image'  =>   'Suite au cours : Allez plus loin avec WordPress',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  true,
		'guthemberg'  =>  true,
		'elementor'  =>  false,
		'link'  =>  'https://bricotips.sanoecreation.fr',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  1106,
		'origine'  =>  'OpenClassrooms',
		'type'  =>  'exercice',
		'title'  =>  'Les bonnes pieces',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours : Créez des pages web dynamiques avec Javascript',
		'image'  =>  'les-bonnes-pieces.png',
		'alt_image'  =>  'Page de gestion de pièces détachées',
		'title_image'  =>   'Suite au cours : Créez des pages web dynamiques avec Javascript',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  '',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  false,
	],

	[
		'realization_id'  =>  2001,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'Helium',
		'description'  =>  'Version avec uniquement HTML et CSS',
		'full_description'  =>  'Suite au cours sur le HTML et le CSS : Découper et faire l\'intégration d\'un site à partir d\'une image et en utilisant FlexBox',
		'image'  =>  'helium.png',
		'alt_image'  =>  'Site Helium',
		'title_image'  =>   'Suite au cours sur le HTML et le CSS : Découper et faire l\'intégration d\'un site à partir d\'une image et en utilisant FlexBox',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/helium/sans-js/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  2002,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'Helium',
		'description'  =>  'Version complète (Html, CSS et JS)',
		'full_description'  =>  'Suite au cours sur le HTML, le CSS et JavaScript : Découper et faire l\'intégration d\'un site à partir d\'une image et en utilisant FlexBox',
		'image'  =>  'helium.png',
		'alt_image'  =>  'Site Helium',
		'title_image'  =>   'Suite au cours sur le HTML, le CSS et JavaScript : Découper et faire l\'intégration d\'un site à partir d\'une image et en utilisant FlexBox',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/helium/avec-js/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  2003,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'Gaming Campus',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours sur le HTML et le CSS : Découper et faire l\'intégration d\'un site à partir d\'une image',
		'image'  =>  'gaming-campus.png',
		'alt_image'  =>  'Site Gaming Campus',
		'title_image'  =>   'Suite au cours sur le HTML et le CSS : Découper et faire l\'intégration d\'un site à partir d\'une image',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/gaming-campus/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  2004,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'RUN',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours sur le HTML et le CSS :  Découper et faire l\'intégration d\'un site à partir d\'une image',
		'image'  =>  'run.png',
		'alt_image'  =>  'Site RUN',
		'title_image'  =>   'Suite au cours sur le HTML et le CSS :  Découper et faire l\'intégration d\'un site à partir d\'une image',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/run/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  2005,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'Générateur de bulles',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours sur le HTML et le CSS : gestion des éléments du DOM avec JavaScript.',
		'image'  =>  'bubble.png',
		'alt_image'  =>  'Le générateur de Bulle',
		'title_image'  =>   'Suite au cours sur le HTML et le CSS : gestion des éléments du DOM avec JavaScript.',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/bubble/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  2006,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'Scroll Popup',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours pour apprendre à gérer une popup en fonction du scroll avec JS',
		'image'  =>  'scroll-popup.png',
		'alt_image'  =>  'Gestion du scroll',
		'title_image'  =>   'Popup qui s\'affiche ou se cache en fonction du scroll',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/scroll-popup/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  2007,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'Sidebar',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours pour apprendre à gérer une Nav bar verticale en fonction de la position de la souris avec JS ',
		'image'  =>  'sidebar.png',
		'alt_image'  =>  'Site Sidebar',
		'title_image'  =>   'Nav bar verticale qui se cache',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/sidebar/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  2008,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'Générateur de mots de passes',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours pour apprendre à gérer les éléments du Dom avec JS ',
		'image'  =>  'password-maker.png',
		'alt_image'  =>  'Le générateur de mots de passes',
		'title_image'  =>   'Le générateur de mots de passes',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/password-maker/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  2009,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'Génération couleur aléatoire',
		'description'  => '' ,
		'full_description'  =>  'Suite au cours pour apprendre à gérer les éléments du Dom avec JS',
		'image'  =>  'color-generator.png',
		'alt_image'  =>  'Générateur de couleurs aléatoires',
		'title_image'  =>   'Change automatiquement la couleur du fond et avec une couleur aléatoire',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/color-generator/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  2010,
		'origine'  =>  'From Scratch',
		'type'  =>  'exercice',
		'title'  =>  'Calculatrice',
		'description'  =>  'Simple calculatrice en JS',
		'full_description'  =>  'Suite au cours pour apprendre à gérer les éléments du Dom avec JS',
		'image'  =>  'calculatrice_2.png',
		'alt_image'  =>  'Calculatrice',
		'title_image'  =>   'Simple calculatrice en JS',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/FromScratch/calculatrice/index.html',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  true,
	],

	[
		'realization_id'  =>  3000,
		'origine'  =>  'Stéphane Mouron',
		'type'  => 'perso',
		'title'  =>  'Portfolio basique',
		'description'  => '' ,
		'full_description'  =>  'Page qui liste tous les projets où j\'ai participé comme développeur. Que cela soit durant le parcours de formation avec OpenClassrooms, du programme de formation de From Scratch ou à titre personnel. 
Projet débuté avec html avant la version avec WorPress. Puis migré en version Php.',
		'image'  =>  'portfolio.png',
		'alt_image'  =>  'Portfolio Stéphane Mouron',
		'title_image'  =>   'Page qui liste tous les projets où j\'ai participé comme développeur.',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/OpenClassrooms.php',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  false,
	],

	[
		'realization_id'  =>  3001,
		'origine'  =>  'Stéphane Mouron',
		'type'  =>  'perso',
		'title'  =>  'Copie de OpenClassrooms',
		'description'  =>  'Essais de reproduire une page de OpenClassrooms (uniquement la partie HTML / CSS)',
		'full_description'  =>  'Site créé pour faire mes essais de découpage de page HTML et de mise en page CSS.',
		'image'  =>  'copie_openclassrooms.png',
		'alt_image'  =>  'Copie de OpenClassrooms',
		'title_image'  =>   'Site créé pour faire mes essais HTML et CSS.',
		'html'  =>  true,
		'js'  => false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  'https://stephane-mouron.fr/perso/copie_OpenClassrooms/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  false,
	],

	[
		'realization_id'  =>  3002,
		'origine'  =>  'Stéphane Mouron',
		'type'  =>  'perso',
		'title'  =>  'Yorkcity',
		'description'  =>  'Lieux intéressants dans la ville de York',
		'full_description'  =>  'Site créé à la base pour une utilisation personnelle par ma fille qui est partie 1 an pour étudier à York. Puis mise à disposition de tout le monde.',
		'image'  =>  'yorkcity.png',
		'alt_image'  =>  'Lieux intéressants dans la ville de York',
		'title_image'  =>   'Site créé à la base pour une utilisation personnelle.',
		'html'  =>  true,
		'js'  =>  true,
		'jquery'  =>  true,
		'css'  =>  true,
		'php'  =>  true,
		'wordpress'  =>  true,
		'guthemberg'  =>  true,
		'elementor'  =>  false,
		'link'  =>  'https://www.sanoecreation.fr/yorkcity/',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  false,
	],

	[
		'realization_id'  =>  3003,
		'origine'  =>  'Stéphane Mouron',
		'type'  =>  'perso',
		'title'  =>  'Outils Web',
		'description'  =>  'Liste de librairies et d\'outils en ligne',
		'full_description'  =>  'Regroupement de tous les liens que j\'ai récupéré un peu partout sur internet et durant les cours d\'OpenClassrooms et de From Scratch.',
		'image'  =>  'outils_web.png',
		'alt_image'  =>  'Liste de librairies et d\'outils en ligne',
		'title_image'  =>   'Regroupement de liens récupéré un peu partout sur internet.',
		'html'  =>  true,
		'js'  =>  false,
		'jquery'  =>  false,
		'css'  =>  true,
		'php'  =>  false,
		'wordpress'  =>  false,
		'guthemberg'  =>  false,
		'elementor'  =>  false,
		'link'  =>  './OutilsWeb.php',
		'github'  =>  '',
		'target'  =>  '_blank',
		'is_enabled'  =>  false,
	],

];

?>

